#!/bin/bash

if [[ ! -d site ]]; then
  echo "No site"
  exit 255
fi

if ! git fetch --depth=1 origin gh-pages; then
  git checkout --orphan gh-pages
else
  git checkout --track origin/gh-pages
fi

rm -rf latest
mv site latest
git add latest
git commit -m "build $CIRCLE_BUILD_NUM"
git push origin gh-pages:gh-pages
