#!/bin/bash

set -e

if [[ -d /tmp/ssh ]]; then
  rm -rf /root/.ssh
  cp -r /tmp/ssh /root/.ssh
  chown -R root /root/.ssh
fi

if [[ ! -d site ]]; then
  echo "No site"
  exit 255
fi
cp -r site /tmp/site

if ! git fetch --depth=1 origin gh-pages; then
  git checkout --orphan gh-pages
  rm -rf *
else
  git checkout --track origin/gh-pages
fi

rm -rf latest
mv /tmp/site latest
git add latest
git commit -m "$1"
git push origin gh-pages:gh-pages
